---

- name: create VPC
  ec2_vpc_net:
         name:             "{{ vpc_name }}"
         cidr_block:       "{{ vpc_cidr_block }}"
         region:           "{{ aws_region }}"
         state:            "present"
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"

  register: my_vpc


- name:  Set VPC ID in variable
  set_fact:
         vpc_id: "{{ my_vpc.vpc.id }}"


- name: Create Public Subnet
  ec2_vpc_subnet:
    state:            "present"
    vpc_id:           "{{ vpc_id }}"
    cidr:             "{{ public_subnet_1_cidr }}"
    az:               "{{ aws_region }}a"
    region:           "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

    resource_tags:
         Name:           "Public Subnet"
  register: my_public_subnet


- name: Set Public Subnet ID in variable
  set_fact:
         public_subnet_id: "{{ my_public_subnet.subnet.id }}"


- name: Create Private Subnet
  ec2_vpc_subnet:
    state: "present"
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ private_subnet_1_cidr }}"
    az: "{{ aws_region }}a"
    region: "{{ aws_region }}"
    resource_tags:
         Name: "Private Subnet"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

  register:  my_private_subnet

- name: Create Internet Gateway for VPC
  ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    state: "present"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

  register: my_vpc_igw


- name: Set Internet Gateway ID in variable
  set_fact:
    igw_id: "{{ my_vpc_igw.gateway_id }}"


- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

    routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_id }}"
  register: public_route_table

